# Generated by Django 6.0.4 on 2026-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(max_length=100)),
                ('case_material', models.CharField(max_length=100)),
                ('strap_material', models.CharField(max_length=100)),
                ('dial_color', models.CharField(max_length=100)),
                ('water_resistance', models.CharField(max_length=50)),
                ('case_size', models.CharField(max_length=50)),
                ('power_reserve', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
